#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

source $OPENSHIFT_HOMEDIR/python/virtenv/venv/bin/activate

if [ ! -f "$OPENSHIFT_HOMEDIR"python/virtenv/venv/lib/python3.3/site-packages/haystack/backends/whoosh_cn_backend.py ]
then
    cp "$OPENSHIFT_REPO_DIR"wsgi/sourcewhoosh_cn_backend.py "$OPENSHIFT_HOMEDIR"python/virtenv/venv/lib/python3.3/site-packages/haystack/backends/whoosh_cn_backend.py
fi

# create database folder if not exist
if [ ! -d "$OPENSHIFT_DATA_DIR"database ]
then
    mkdir "$OPENSHIFT_DATA_DIR"database
fi

if [ ! -d "$OPENSHIFT_DATA_DIR"whoosh ]
then
    mkdir "$OPENSHIFT_DATA_DIR"whoosh
fi

# create media folder if not exist
if [ ! -d "$OPENSHIFT_DATA_DIR"media ]
then
    mkdir "$OPENSHIFT_DATA_DIR"media
fi


# if static folder not exist, create one
if [ ! -d "$OPENSHIFT_REPO_DIR"wsgi/static ]
then
    mkdir "$OPENSHIFT_REPO_DIR"wsgi/static
fi



# if [ ! -f "$OPENSHIFT_DATA_DIR"database/db.sqlite3 ]
# then
#     echo "Copying "$OPENSHIFT_REPO_DIR"wsgi/source/db.sqlite3 to $OPENSHIFT_DATA_DIR"
#     cp "$OPENSHIFT_REPO_DIR"database/db.sqlite3 "$OPENSHIFT_DATA_DIR"database/
#     #python "$OPENSHIFT_REPO_DIR".openshift/action_hooks/secure_db.py | tee ${OPENSHIFT_DATA_DIR}/CREDENTIALS
# else
#     echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/source/manage.py syncdb --noinput'"
#     python "$OPENSHIFT_REPO_DIR"wsgi/source/manage.py migrate --noinput
# fi

python "$OPENSHIFT_REPO_DIR"wsgi/source/manage.py syncdb --noinput
python "$OPENSHIFT_REPO_DIR"wsgi/source/manage.py makemigrations --noinput
python "$OPENSHIFT_REPO_DIR"wsgi/source/manage.py migrate --noinput

# if json file exist load the file and import to database
if [ -f "$OPENSHIFT_DATA_DIR"database/datadump.json ]
then
python "$OPENSHIFT_REPO_DIR"wsgi/source/manage.py loaddata "$OPENSHIFT_DATA_DIR"database/datadump.json
fi

SEARCH_ENGINE="WATSON"
if [ $SEARCH_ENGINE = "HAYSTACK" ]
then
    echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/source/manage.py update_index --noinput'"
    python "$OPENSHIFT_REPO_DIR"wsgi/source/manage.py update_index --noinput
else
    # watson build
    python "$OPENSHIFT_REPO_DIR"wsgi/source/manage.py installwatson
    echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/source/manage.py buildwatson'"
    python "$OPENSHIFT_REPO_DIR"wsgi/source/manage.py buildwatson
fi
echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/source/manage.py collectstatic --noinput'"
python "$OPENSHIFT_REPO_DIR"wsgi/source/manage.py collectstatic -c --noinput
